FROM python:3.13-slim

COPY . .
WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# TODO: optimize gunicorn for hardware (https://medium.com/@iklobato/mastering-gunicorn-and-uvicorn-the-right-way-to-deploy-fastapi-applications-aaa06849841e)
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
CMD ["gunicorn", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker",  "--bind", "0.0.0.0:80", "--worker-connections", "1000", "main:app"]

# generated by deepseek
# FROM python:3.9-slim

# WORKDIR /src

# # Install system dependencies
# RUN apt-get update && apt-get install -y \
#     libgl1-mesa-glx \
#     libglib2.0-0 \
#     && rm -rf /var/lib/apt/lists/*

# # Copy requirements and install Python dependencies
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# # Copy application code
# COPY . .

# # Run as non-root user
# RUN useradd -m -u 1000 appuser
# USER appuser

# # Production settings
# ENV PYTHONUNBUFFERED=1
# ENV MAX_CONCURRENT_REQUESTS=10
# ENV THREAD_POOL_WORKERS=2

# CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8888", "--workers", "1"]